return {
  {
    "nvim-treesitter/nvim-treesitter",
    optional = true,
    opts = {
      ensure_installed = {
        "bash",
        "diff",
        "go",
        "gomod",
        "gosum",
        "gowork",
        "html",
        "javascript",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "ron",
        "rst",
        "rust",
        "svelte",
        "toml",
        "tsx",
        "typescript",
        "xml",
        "yaml",
      },
    },
  },
}
